version: '3.8'

services:
  jwt:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend-jwt
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    depends_on:
      - db
    networks:
      - net

  db:
    image: postgres:alpine
    container_name: trabajojwt-db
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - "4444:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    
    networks:
      - net

 
volumes:
  postgres_data:

networks:
  net:
    driver: bridge