services:
  jwt:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend-jwt
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    networks:
      - net

  db:
    image: postgres:alpine
    container_name: trabajojwt-db
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - "4444:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 2s
      retries: 5
    networks:
      - net

volumes:
  postgres_data:

networks:
  net:
