

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend-jwt
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
