services:
  jwt:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend-jwt
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    depends_on:
      - db
    networks:
      - net

  db:
    image: postgres:alpine
    container_name: trabajojwt-db
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - "4444:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - net


  db-init:
    image: postgres:alpine
    container_name: db-init
    depends_on:
      - db
    entrypoint: ["sh", "-c", "sleep 10 && PGPASSWORD=postgres psql -h db -U postgres -d postgres -f /init.sql"]
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./sql/init.sql:/init.sql:ro
    networks:
      - net
    restart: "no"


volumes:
  postgres_data:

networks:
  net:
    driver: bridge

# docker exec -it trabajojwt-db psql -U postgres -d postgres