# Usar la imagen oficial de Node.js
FROM node:18.19.1

# Establecer el directorio de trabajo dentro del contenedor
WORKDIR /usr/src/app

# Copiar solo los archivos de dependencias para aprovechar el cache de Docker.
COPY package*.json ./

# **** PASO DE DEPURACIÓN ****
RUN ls -l /usr/src/app/

# Instalar las dependencias del proyecto
RUN npm install

# Copiar el resto del código fuente del proyecto
COPY . .

# Compilar el proyecto (si es necesario para tu start:dev)
RUN npm run build

# Exponer el puerto que usa la aplicación
EXPOSE 3000

# Comando por defecto para iniciar la aplicación en modo desarrollo
CMD [ "npm", "run", "start:dev" ]