# frontend/Dockerfile
FROM node:18-alpine as builder
WORKDIR /app

# Copiar package*.json desde el directorio padre (.devcontainer -> frontendTPI)
COPY ../package*.json ./

# Instalar dependencias
RUN npm install

# Copiar todo el código desde el directorio padre
COPY ../ .

# Construir la aplicación
RUN npm run build --prod

# Etapa de producción con nginx
FROM nginx:alpine



# Exponer puerto 80 (nginx por defecto)
EXPOSE 80